version: '3'
services:
  app:
    build:
      dockerfile: D:\development-docker\docker-laravel-forestry\_docker\Dockerfile
    image: php:8.2-fpm
    container_name: licenzion-app
    working_dir: /var/www/html
    ports:
      - 8080:8081
    volumes:
      - D:\development-docker\docker-laravel-forestry:/var/www/html
    depends_on:
      - db
  nginx:
      image: nginx:1.19-alpine
      container_name: nginx-licenzion
      ports:
          - 80:80
          - 443:443
      volumes:
          - D:\development-docker\docker-laravel-forestry\_docker\nginx\nginx.conf:/etc/nginx/nginx.conf
          - D:\development-docker\docker-laravel-forestry\_docker\nginx\vhosts:/etc/nginx/conf.d/
          - D:\development-docker\docker-laravel-forestry:/var/www/html
      depends_on:
          - app
  db:
    image: mysql:8.0.33
    container_name: licenzion-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: licenzia
      MYSQL_DATABASE: licenzia
      MYSQL_USER: licenzia
      MYSQL_PASSWORD: licenzia
    ports:
      - 3306:3306
